# Generated by Django 6.0 on 2026-01-16 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categorie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Depense",
            fields=[
                ("iddepense", models.AutoField(primary_key=True, serialize=False)),
                ("nomdep", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("devise", models.CharField(max_length=3)),
                ("date", models.DateField()),
                (
                    "idcat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depenses",
                        to="categorie.categorie",
                    ),
                ),
            ],
        ),
    ]
