# Generated by Django 6.0 on 2026-01-16 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("connexion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                ("idcat", models.AutoField(primary_key=True, serialize=False)),
                ("nomcat", models.CharField(max_length=100)),
                (
                    "matricule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="connexion.connexion",
                    ),
                ),
            ],
        ),
    ]
