# Generated by Django 6.0 on 2026-01-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connexion",
            fields=[
                (
                    "matricule",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=255)),
                ("nom", models.CharField(max_length=50)),
            ],
        ),
    ]
